CSS refactoring to BEM
Romanmaliska/romanmaliska.github.io pull request #1
Opened 2022-05-13 06:21 UTC by Romanmaliska

2022-05-13 07:16 UTC, benabraham requested changes
vše v kódu + tato vylepšení

- [x] unless it's a generic family font name it should be always in quotes
- [ ] `.overheading--dark-blue` and `light-blue` both have the same margin-bottom (should be specified once)
- [ ] `@media (min-width: 800px) { .overheading {…` should be directly after `.overheading…`
- [ ] `.overheading--dark-blue::before` move to separate media query
- [ ]  `.article:first-of-type` after `.article`

2022-05-13 07:16 UTC, benabraham commented on index.html
> +                <div class="header__wrapper">
„Wrapper“ je něco kolem a toto je uvnitř.
Vymysli lepší jméno.
```suggestion
                <div class="header__content">
```

2022-05-13 07:16 UTC, benabraham commented on index.html
> +                        <span class="overheading overheading--dark-blue">Frontend Developer</span>
možná by stačilo „dark“ 🤔

2022-05-13 07:16 UTC, benabraham commented on index.html
>                      <h1>
h1 by mohla, až měla být taky stylovaná v rámci BEM, `header__heading`

2022-05-13 07:16 UTC, benabraham commented on index.html
> +                        <span class="overheading overheading--light-blue">What Can I Work With</span>
opět: stačilo by `overheading--light`, výhoda by byla, že pokud se změní barevnost, dává to pořád smysl

2022-05-13 07:16 UTC, benabraham commented on index.html
> +                <section class="projects__wrapper" id="projects">
Tohle je blok, který obsahuje elementy. Pro slovo wrapper není důvod skoro nikdy.

```suggestion
                <section class="projects" id="projects">
```

2022-05-13 07:16 UTC, benabraham commented on index.html
>                      <h2>
chybí mi třída typu `projects__heading`

2022-05-13 07:16 UTC, benabraham commented on index.html
> +                    <article class="article">
má být součástí komponenty projects
alternativně by mohla být nová komponenta `project`
```suggestion
                    <article class="projects__project">
```

2022-05-13 07:16 UTC, benabraham commented on index.html
>                          <h3>Project Alpha</h3>
```suggestion
                        <h3 class="projects__small-heading">Project Alpha</h3>
```
nebo vymysli lepší název, ale je to součást té komponenty

2022-05-13 07:16 UTC, benabraham commented on index.html
> +                        <div class="article__project">
```suggestion
                        <div class="projects__info">
```

2022-05-13 07:16 UTC, benabraham commented on index.html
>                                      were the technologies and methodologies used
to samé co u předchozího projektu

2022-05-13 07:16 UTC, benabraham commented on index.html
>                                      were the technologies and methodologies used
to samé co u předchozího projektu

2022-05-13 08:41 UTC, Romanmaliska commented on index.html
> +                        <div class="article__project">
renamed class name sshould be "project-info"

2022-05-13 09:14 UTC, Romanmaliska commented on index.html
>                      <h2>
h2 style used also in section outside projects - Other skill section and footer

2022-05-13 09:17 UTC, Romanmaliska commented on index.html
>                      <h2>
For the time being upadated to class name "subheading"

2022-05-16 06:23 UTC, benabraham requested changes

2022-05-16 06:23 UTC, benabraham commented on index.html
> +                        <h3 class="project__small-heading">Project Alpha</h3>
```suggestion
                        <h3 class="projects__small-heading">Project Alpha</h3>
```

2022-05-16 06:23 UTC, benabraham commented on index.html
> +                        <div class="project__info">
```suggestion
                        <div class="projects__info">
```

2022-05-16 06:23 UTC, benabraham commented on index.html
> +                        <h3 class="project__small-heading">Project Beta</h3>
```suggestion
                        <h3 class="projects__small-heading">Project Beta</h3>
```

2022-05-16 06:23 UTC, benabraham commented on index.html
> +                        <div class="project__info">
```suggestion
                        <div class="projects__info">
```

2022-05-16 06:23 UTC, benabraham commented on index.html
> +                        <div class="project__info">
```suggestion
                        <h3 class="projects__small-heading">Project Gamma</h3>
                        <div class="projects__info">
```

2022-05-16 06:23 UTC, benabraham commented on stylesheet.css
> +.header__content,
`.header__content` by asi bylo lepší u `.header` kvůli přehlednosti

2022-05-16 06:23 UTC, benabraham commented on stylesheet.css
> +}
pod `.project`
zvaž přidat i komentáře

2022-05-16 06:40 UTC, benabraham approved these changes
![seal of approval](https://user-images.githubusercontent.com/334494/168533685-a74ec555-1f63-4fa2-ab53-d72653186d7b.png)

2022-05-16 06:45 UTC, merged